name: Build and Compile
on:
  pull_request:
    types:
      - opened

jobs:
  notify_user:
    runs-on: ubuntu-latest
    steps:
      - name: Add PR Comment
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const comment = `
            comment:)
            `
            const { owner, repo } = context.repo;
            const { number } = context.issue;
            github.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: comment
            });
