name: Add Comment to PR
on:
  pull_request:
    types:
      - opened

jobs:
  add-comment:
    runs-on: ubuntu-latest

    steps:
      - name: Add Comment
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const { number } = context.issue;

            const comment = 'לקבל המשתמש - הערה מתוך קובת YAML';
            await octokit.issues.createComment({
              owner,
              repo,
              issue_number: number,
              body: comment,
            });
