name: Build and Compile
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Compile software
      run: tsc

    - name: Notify on failure
      if: ${{ failure() }}
      run: echo "הקמפול נכשל על בראנץ הראשי"



      

