name: Comment on PR
on:
  pull_request:
    types:
      - opened

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Comment on PR
        uses: actions/github-script@v4
        with:
          script: |
            const comment = `PR לקבל: ${process.env.GITHUB_REPOSITORY}`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: comment
            });
          token: ${{ secrets.GITHUB_TOKEN }}

